# Fly.io deployment configuration
app = "concafe-shift-tracker"
primary_region = "nrt"  # Tokyo region

[build]
  dockerfile = "Dockerfile.fly"

[env]
  NODE_ENV = "production"
  PLAYWRIGHT_HEADLESS = "true"
  LOG_LEVEL = "INFO"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "30s"
  timeout = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  tls_skip_verify = false

[processes]
  app = "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"

[[mounts]]
  source = "concafe_data"
  destination = "/data"

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

# Memory and CPU configuration
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024